# Generated by Django 5.1.4 on 2025-02-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_projects', models.IntegerField(default=0, verbose_name='پروژه های انجام شده')),
                ('satisfied_customers', models.IntegerField(default=0, verbose_name='مشتریان راضی')),
                ('members', models.IntegerField(default=0, verbose_name='تعداد اعضای تیم')),
                ('full_support', models.IntegerField(default=0, verbose_name='پشتیبانی')),
            ],
        ),
    ]
