# Generated by Django 5.1.4 on 2025-02-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'مجموعه', 'verbose_name_plural': 'مجموعه ها'},
        ),
    ]
