# Generated by Django 5.1.4 on 2025-02-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
