# Generated by Django 5.1.4 on 2025-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_comment_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=100, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='image/customer', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='مجوز قرار دادن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.IntegerField(verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=225, verbose_name='ایمیل'),
        ),
    ]
