# Generated by Django 5.1.4 on 2025-02-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='نامک')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='نامک')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('budget', models.CharField(max_length=100, verbose_name='بودجه')),
                ('project_manager', models.CharField(max_length=60, verbose_name='مدیر پروژه')),
                ('place', models.CharField(max_length=100, verbose_name='محل')),
                ('website', models.CharField(max_length=100, verbose_name='وب سایت')),
                ('star', models.IntegerField(verbose_name='امتیاز')),
                ('main_image', models.ImageField(upload_to='project', verbose_name='عکس اصلی')),
                ('image1', models.ImageField(upload_to='project', verbose_name='عکس 1')),
                ('image2', models.ImageField(upload_to='project', verbose_name='عکس 2')),
                ('Text1', models.TextField(verbose_name='متن یک, پاراگراف طراحی')),
                ('Text2', models.TextField(verbose_name='متن دو, پاراگراف نکات')),
                ('Text3', models.TextField(verbose_name='متن یک, پاراگراف نمای کلی چالش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
