# Generated by Django 5.1.4 on 2025-02-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Text1',
            field=models.TextField(verbose_name='متن یک, توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Text2',
            field=models.TextField(verbose_name='متن دو, نکات پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Text3',
            field=models.TextField(verbose_name='متن سوم, نمای کلی و چالش ها'),
        ),
    ]
