# Generated by Django 5.1.4 on 2025-02-06 13:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Text1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Text2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Text3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='محتوای پروژه'),
        ),
    ]
